module Content.Posts exposing (Post, posts)

{-| The written record. Newest first.

To add a field note:

1. append a body constant at the bottom of this file
2. add one metadata record to `posts` (newest first)
3. run ./build.sh — rss.xml + sitemap.xml are regenerated from this file
-}


-- MODEL ---------------------------------------------------------------------


type alias Post =
    { slug : String
    , number : Int -- FIELD NOTE nn, assigned chronologically
    , title : String
    , description : String
    , tags : List String
    , status : String -- complete | drafting | unfinished
    , body : String
    }


-- INDEX ----------------------------------------------------------------------


posts : List Post
posts =
    [ { slug = "2026-07-21-i-read-code"
      , number = 1
      , title = "I read the code."
      , description = """“I read the code” is the highest-signal advice in software. A protocol for reading source like an engineer instead of a tourist."""
      , tags = [ "craft", "reading-code" ]
      , status = "complete"
      , body = readCodePost
      }
    , { slug = "2026-07-18-redesigning-plast"
      , number = 2
      , title = "Re-designing Plast for a more elegant solution"
      , description = """Treating the training stack as a black box stopped being fun. Notes from rebuilding a deep learning engine from autograd up."""
      , tags = [ "plast", "deep-learning", "cuda" ]
      , status = "complete"
      , body = plastPost
      }
    , { slug = "2026-07-09-zig"
      , number = 3
      , title = "Why I fell in love with Zig"
      , description = """Comptime, no hidden control flow, errors as values — notes on why Zig feels like the first language that respects the programmer since C."""
      , tags = [ "zig", "systems", "languages" ]
      , status = "complete"
      , body = zigPost
      }
    , { slug = "2026-06-20-what-I-have-learnt-building-a-SaaS-startup"
      , number = 4
      , title = "What I Learnt Building a SaaS"
      , description = """Five months inside a startup taught me what the ecosystem actually optimizes for. Field notes from stripping an AI-SIEM hackathon demo down into a real engine."""
      , tags = [ "startups", "systems", "culture" ]
      , status = "complete"
      , body = saasPost
      }
    ]


-- BODIES ---------------------------------------------------------------------


readCodePost : String
readCodePost =
    """# I read the code.

## The tweet

"I read the code." is a tweet posted by Mitchell Hashimoto, the creator of Ghostty and co-founder of HashiCorp. It started a debate over the internet about whether people should read the slop generated by AI coding agents or not.

First of all, I'm not going to address the dumb "AI as a compiler" take. The only thing you get out of this argument is knowing the person saying it doesn't know shit about compilers or LLMs. If you're willing to spread shitty arguments without understanding the technology, get the fuck out of tech and find something you're actually willing to learn.

## When AI works without reading

You have a trivial app you use for yourself a couple times and you don't care how it works. You're not going to maintain or scale it. Here the AI is perfect. It just gives you what you want in very little time. Big win.

## The zero-dependency trap

So I've been thinking a lot about the role of AI in programming, and there are a lot of ideas. But here's an interesting hypothesis. Say we use AI coding agents to make our code zero-dependency. Sounds nice, huh? The AI builds you the helpers or the low-level stuff you don't understand and exposes a simple API. It's like importing a third-party library without actually adding a dependency. And zero-dependency code is great, right? It lets you work on projects out of your league right now. But in fact it's very bad. Using a third-party library is actually better than going zero-dep. What? How? I'll tell you.

We don't really think about this when we use a third-party dependency, but when we do, we're implicitly trusting the maintainers to keep it working with good performance. You don't need to care about the library. It's all trust.

With AI-generated code, the code is sitting in your codebase, which makes it officially your problem — not someone else's. So now you're implicitly trusting the AI agent to maintain this code and meet your application's functional and non-functional requirements. That's a real problem if you actually understand how AI works under the hood. And by now, it seems like the big majority are just pretending to know.

## The 500K lines scenario

Humans have been generating slop for decades. We write bad code with massive technical debt and abstractions that kill performance. So why is AI much different? Let me paint a scenario. You had AI author a non-trivial piece of software (I'm too lazy to think of a specific example). You don't review any of it. You let the AI do whatever it wants. Now it's generated a 500K+ line codebase. Congrats, your code has users. Bug reports start coming in. Feature requests pile up. Maybe it's a SaaS and you need to scale. In this scenario you're completely fucked. Here's why.

Let's start with what we can measure. Our biggest AI models have around 1M tokens of context window. Solid, right? But in our scenario you have 500K+ lines of code you know nothing about. You have a logical bug and you need to fix it. How? You go to an LLM, tell it "solve this bug plsss." It loads the whole codebase and burns through the entire context window looking for candidates in the over-engineered mess it created. It tries to debug. It fails — because it just exhausted most of its context tokens. 1M tokens is roughly 750K words depending on the tokenizer. It's trying to fit the codebase plus all its thinking into that. And yeah, I know you can use `AGENT.md`, `CLAUDE.md`, all those markdown files you read about on LinkedIn. The codebase is still too large.

You'll tell me: hahaha, you're dumb, "solve this bug plsss." is a stupid prompt, I can write a better one. And I'll tell you that as humans we also have context windows. AI mimics our intelligence. In this scenario you don't know shit about the codebase. You don't know how it's organized, where the code lives, how any of the logic works. You have zero context about the problem. And it's simple: if you don't understand the problem, you can't solve it. Just like that.

Now if you were actually reading the code the AI generates, you'd know where the bug likely is. You do some simple debugging, feed the LLM the relevant places, give it the debugging session results, and tell it the expected behaviour. It solves the problem with way fewer tokens. That means more money saved. If it solves your problem but costs way more than it should, that's not good after all.

---

## So will AI get better?

Let's talk about if AI is actually going to get better — good enough that reading doesn't matter.

First, the cost. You'll say: it solves everything, it'll get cheaper like all technology, right? I don't think AI is getting cheaper. Not with the current market conditions. Anthropic and OpenAI are consistently losing money because they underprice their model serving. Which means it should actually get more expensive. You'll say: but China's models are great. And I agree — long live open-source. But that doesn't really solve the problem. It's cheap now, but it's not going to get cheaper. It will only get more expensive. With each new SOTA, the param count grows. Kimi k2 just dropped with 2.8 TRILLION params. Insane.

And these massive models don't just cost more in API tokens — they need more expensive hardware to run at all. More params means you need GPUs with way more VRAM, which cost a fortune and draw insane amounts of power. Running inference on a 2.8T param model is incredibly inefficient compared to a smaller, fine-tuned model that could do the same job. So even if the API is cheap today, the underlying economics make no sense at scale.

And here is the thing: the companies building these models don't really have an incentive to make the AI generate less code. Less code means less tokens, and less tokens means less money. They are not going to optimize for conciseness when their business model is selling you tokens. So you're stuck paying for bloated, over-engineered solutions.

Second, the quality problem. AI is still generating over-engineered code with bad abstractions and patterns. You will find yourself in a codebase that could have been much smaller, more elegant. And it's not the LLMs' fault. They're trained on human code, and we generate bad code by definition. Good design isn't objective — you can't enforce it with a deterministic feedback loop. There's no reward signal for clean architecture.

And the most active direction in AI research is architectural hacks to increase params and context window — not better foundational models that could actually change how language generation works. I'm a huge believer in the world model architecture Yann LeCun introduced. But we still don't have evidence it will deliver here.

This should make it obvious. AI will let you down at some point. And at that moment, you'll have to figure it out yourself.

## Your own slop is better than AI slop

At this point you don't have a fucking clue how anything works. So the velocity you gained getting to market? It essentially backfires. The time you saved? You're paying it back to refactor and understand the project.

So if I'm a bad programmer who writes slop, at least it's my own slop. I understand it. I can operate within it. (If you're a web developer who uses TypeScript, you don't have the right to call anyone's code slop tbh.)"""


plastPost : String
plastPost =
    """# Re-designing Plast for more elegant solution

Over the last couple of weeks I have been working on my robotics communication framework in Zig. I finalized the core for the first version that I will publish, so I thought it's a good time to go work on something else for a couple of days so I don't burn out — the project was starting to feel boring. I'm very interested in Physical AI and robotics, so I decided to go back to `plast`, which is my simple deep learning framework written in `c` and `cuda`. I already implemented the cpu and gpu kernels for most of the tensor ops needed, built a tiny `JIT` compiler for it, and made python bindings so people can use it with an experiment tracking system. But there is something else. As someone interested in physical AI and robotics, this library is useless to me without the ability to do reinforcement learning with ease.

## Why rewrite in Zig?

I think this shouldn't be a shocker by now. I invested a good amount of time learning and writing Zig, and built glu from scratch in pure Zig. To be honest, writing python code for robots is not ideal — you don't get much control over your resources. And writing the api in c is not the most enjoyable experience you can get. So re-writing the core in Zig is a win. It's a good mixture of both worlds: I still have fine-grained control over hardware resources, and I get a decent api that is enjoyable to work with.

"But rewriting a full deep learning framework from scratch seems like a premature decision that will take too much time." I figured you might ask that. And maybe you'd be correct. But the project wasn't that big. Running `cloc . --exclude-content=kernels/ --exclude-lang=zig` on my `src/` folder gives me this:

```
-------------------------------------------------------------------------------
Language                     files          blank        comment           code
-------------------------------------------------------------------------------
C                               11            122             12            755
C++                              1             37              9            294
CUDA                             6             30              7            181
-------------------------------------------------------------------------------
SUM:                            18            189             28           1230
-------------------------------------------------------------------------------
```

Most of the code lives in the `kernels/` folder with the `c` and `cuda` kernels. The project wasn't that large after all. So I decided to re-write the core in Zig, keep the kernels, and just use the `extern` keyword to link them in the build system. Same kernels, no re-write, but now the system is in a language I can actually enjoy working with. Win-win.

## The problem with hand-written kernels

The approach I'm using right now is hand-writing every single kernel for every operation. This is not ideal. First, it means too much code. In `c` that means writing optimized kernels for every data type. When writing `cuda` kernels, the execution configuration alone can make or break performance. And one of the most important optimization techniques in ML compilers — kernel fusion — becomes a nightmare of combinatorial explosion.

Kernel fusion is about writing a single kernel that composes multiple operations together. Take the most used `nn` layer in deep learning: `Linear`, which is basically `input @ weight.T + bias`. Why load `input` and `weights` from memory, do matmul, store the output, then load that result back to add `bias`, then store again? If you have been paying attention (congrats for not being brain-rotted) you'll notice we just did `(4) loads` and `(2) stores` across two separate function frames with jump operations in between. That shit is a performance killer.

With kernel fusion we write a single `matmul_add` kernel: matmul then add in the same frame. No jump ops. In this version we do `(3) loads` and `(1) store`. We saved one load and one store, which is significant because loads and stores are the most expensive operations in computer hardware.

With hand-written kernels we would need to write every fused variant separately, and all of them need to be exported to Zig. Plus the code is ugly. Look at this:

```cuda
__global__ void add_kernel_float_contig(const float *a, const float *b, float *c, int num_elements) {
    int tid = blockDim.x * blockIdx.x + threadIdx.x;

    if (tid < num_elements) {
        c[tid] = a[tid] + b[tid];
    }
}

__global__ void add_kernel_int_contig(const int *a, const int *b, int *c, int num_elements) {
    int tid = blockDim.x * blockIdx.x + threadIdx.x;

    if (tid < num_elements) {
        c[tid] = a[tid] + b[tid];
    }
}

__global__ void sub_kernel_float_contig(const float *a, const float *b, float *c, int num_elements) {
    int tid = blockDim.x * blockIdx.x + threadIdx.x;

    if (tid < num_elements) {
        c[tid] = a[tid] - b[tid];
    }
}

__global__ void sub_kernel_int_contig(const int *a, const int *b, int *c, int num_elements) {
    int tid = blockDim.x * blockIdx.x + threadIdx.x;

    if (tid < num_elements) {
        c[tid] = a[tid] - b[tid];
    }
}


__global__ void mul_kernel_float_contig(const float *a, const float *b, float *c, int num_elements) {
    int tid = blockDim.x * blockIdx.x + threadIdx.x;

    if (tid < num_elements) {
        c[tid] = a[tid] * b[tid];
    }
}

__global__ void mul_kernel_int_contig(const int *a, const int *b, int *c, int num_elements) {
    int tid = blockDim.x * blockIdx.x + threadIdx.x;

    if (tid < num_elements) {
        c[tid] = a[tid] * b[tid];
    }
}
```

And this is only for two data types, without even considering noncontiguous data layouts from slicing and movement ops like `broadcast` and `expand`.

## Codegen to the rescue

As a big fan of geohot, I was very interested in studying how tinygrad works. Tinygrad has a similar philosophy to `tvm`. Here's how `tvm` works: it captures the computation graph, lowers it to an `IR` representation, optimizes it with `MLIR`, and executes the optimized graph.

Tinygrad doesn't work exactly the same way, but the philosophy is similar. Instead of hand-writing every kernel — which is what I'm doing in plast — it has a `codegen` module. This module uses the `UOp` datatype to write kernels at runtime as needed. Using something called a `Linearizer`, it tries different optimization techniques like loop unrolling and shared memory usage on cuda, launches kernels with different configurations, and uses Beam Search to pick the fastest one.

You might think "this is very slow". You're not completely right, but you're not completely wrong either. It's slower on the first batch because it has to build the graph and write the optimized kernels. But with a JIT compiler we cache the resulting graph and kernels, so every subsequent batch uses them directly. This gives us a highly optimized graph without writing a kernel for every single combination of constraints.

Now let's look at how to generate all those ugly kernels from the previous section on the fly:

```zig
const std = @import("std");

pub const DataType = enum {
    float,
    int,

    pub fn toCudaTypeString(self: DataType) []const u8 {
        return switch (self) {
            .float => "float",
            .int => "int",
        };
    }
};

pub const OpType = enum {
    add,
    sub,
    mul,

    pub fn toChar(self: OpType) u8 {
        return switch (self) {
            .add => '+',
            .sub => '-',
            .mul => '*',
        };
    }
};

pub const Op = struct {
    op_type: OpType,
    data_type: DataType,

    pub fn generateKernel(self: Op, allocator: std.mem.Allocator) ![]const u8 {
        const op_name = @tagName(self.op_type);
        const type_name = @tagName(self.data_type);
        const type_c_str = self.data_type.toCudaTypeString();
        const op_char = self.op_type.toChar();

        const template =
            \\\\\\\\__global__ void {s}_kernel_{s}_contig(const {s} *a, const {s} *b, {s} *c, int num_elements) {{
            \\\\\\\\    int tid = blockDim.x * blockIdx.x + threadIdx.x;
            \\\\\\\\
            \\\\\\\\    if (tid < num_elements) {{
            \\\\\\\\        c[tid] = a[tid] {c} b[tid];
            \\\\\\\\    }}
            \\\\\\\\}}
            \\\\\\\\
        ;

        return try std.fmt.allocPrint(allocator, template, .{
            op_name,
            type_name,
            type_c_str,
            type_c_str,
            type_c_str,
            op_char,
        });
    }
};
```

With this we can generate kernels for any data type we want. With the right implementation, generating optimized kernels becomes elegant and maintainable instead of a copy-paste factory. That's why I think codegen is a much better approach than hand-written kernels.

## What's next for Plast

So where does this leave us? The plan is coming together: rewrite the core in Zig, keep the existing kernels, build a codegen module to replace the kernel copy-paste nightmare, wire it all into the JIT compiler, and finally — finally — have a framework I can actually use for reinforcement learning without wanting to throw my laptop out the window.

Right now I'm working on the Zig core and the codegen module in parallel. The kernels are already done and battle-tested from the C version, so that part is essentially free — just link and go. Once the codegen is mature enough to handle the full set of elementwise ops, I'll start fuzzing it against the hand-written kernels to make sure we don't regress on correctness or performance. After that, the hand-written versions go in the trash where they belong.

I don't know when the first version will be ready. Could be weeks, could be months. But for the first time this project actually feels fun again, and that's worth more than any release date."""


zigPost : String
zigPost =
    """# Why I fell in love with Zig

Over the last couple of weeks, I set out to learn Zig. I went into it assuming it would be just another bloated piece of software weighed down by too many layers of abstraction—the kind that makes a language more complex instead of making development easier.

The last language that gave me that headache was Rust. Don't get me wrong, Rust's ownership model for managing memory is clever. But for me, it's just not worth dealing with all the unnecessary complexity Rust forces on you while you work. To put it simply: Rust is just not fun to write or read.

Some people will claim Rust is more fun than a language like Go because Go is "too repetitive", or something like that, and my only response to that is: "go work on real problems, bro." as the fun, creative thinking should be spent solving the actual problem at hand—not fighting the language's syntax or trying to figure out which hyper-abstract concept you need to implement basic logic.

So, what makes Zig so great, besides its simplicity?

---

## comptime

`comptime` is absolutely incredible. It is a massive upgrade over C/C++ macros and Rust's `proc_macro`. It is so intuitive and easy to use because it flows naturally with the rest of the program.

### C Approach: Preprocessor Magic
```c
#include <stdio.h>
#include <stdbool.h>

// The "Macro Template"
#define DECLARE_STACK(Type, Name, Capacity) \\\\
    typedef struct { \\\\
        Type data[Capacity]; \\\\
        size_t top; \\\\
    } Name; \\\\
    \\\\
    static inline void Name##_push(Name* s, Type item) { \\\\
        if (s->top < Capacity) { \\\\
            s->data[s->top++] = item; \\\\
        } \\\\
    } \\\\
    \\\\
    static inline Type Name##_pop(Name* s) { \\\\
        return s->data[--s->top]; \\\\
    }

// Generating a specific type: IntStack
DECLARE_STACK(int, IntStack, 10)

int main() {
    IntStack stack = { .top = 0 };
    IntStack_push(&stack, 42);
    printf("%d\\n", IntStack_pop(&stack));
    return 0;
}
```

### Rust Approach: Procedural Macros
```rust
extern crate proc_macro;
use proc_macro::TokenStream;
use quote::quote;
use syn::{parse_macro_input, Expr, Type, parse::Parse, parse::ParseStream, Token};

// A custom parser struct to handle: Stack!(i32, 10)
struct StackArgs {
    ty: Type,
    _comma: Token![,],
    cap: Expr,
}

impl Parse for StackArgs {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        Ok(StackArgs {
            ty: input.parse()?,
            _comma: input.parse()?,
            cap: input.parse()?,
        })
    }
}

#[proc_macro]
pub fn make_stack(input: TokenStream) -> TokenStream {
    let StackArgs { ty, cap, .. } = parse_macro_input!(input as StackArgs);

    let expanded = quote! {
        struct Stack {
            data: [#ty; #cap],
            top: usize,
        }

        impl Stack {
            fn new() -> Self { Self { data: [0; #cap], top: 0 } } // Simplification
            fn push(&mut self, item: #ty) {
                if self.top < #cap {
                    self.data[self.top] = item;
                    self.top += 1;
                }
            }
            fn pop(&mut self) -> #ty {
                self.top -= 1;
                self.data[self.top]
            }
        }
    };
    TokenStream::from(expanded)
}

// Generates the struct and implementation at compile time
make_stack!(i32, 10); 

fn main() {
    let mut s = Stack::new();
    s.push(100);
    println!("{}", s.pop());
}
```

### Zig Approach: comptime
```zig
const std = @import("std");

// Just a normal function, but it returns a `type` 
// and takes compile-time arguments.
fn Stack(comptime T: type, comptime capacity: usize) type {
    return struct {
        data: [capacity]T = undefined,
        top: usize = 0,

        const Self = @this();

        pub fn push(self: *Self, item: T) void {
            if (self.top < capacity) {
                self.data[self.top] = item;
                self.top += 1;
            }
        }

        pub fn pop(self: *Self) T {
            self.top -= 1;
            return self.data[self.top];
        }
    };
}

pub fn main() !void {
    // Instantiating the type naturally
    var my_stack = Stack(i32, 10){};
    
    my_stack.push(1337);
    std.debug.print("{d}\\n", .{my_stack.pop()});
}
```

If you have any taste for programming, you can clearly see that the `comptime` solution is miles ahead in terms of elegance.

---

## How Zig Proved That Adding More Abstractions Isn't the Answer

It is fascinating to me how Rust and C++ tried to "fix" C by stacking layers of abstraction on top of it, only to end up being bloated, complicated, and a chore to read and write. Meanwhile, Zig took a different path: it removed some of the few implicit abstractions C actually has (like hidden memory allocations and magic I/O), giving us a language that is both incredibly simple and fun to work with.

By now, it's probably obvious that I'm a massive fan of having no hidden allocations, no hidden control flow, and no preprocessor magic. This philosophy makes your code predictable and debugging infinitely easier.

### Explicit Memory Allocation

```zig
const std = @import("std");

pub fn main() !void {
    // 1. Explicit Memory Strategy
    // We explicitly choose a General Purpose Allocator. The runtime does not hide this.
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    defer _ = gpa.deinit(); // Enforce leak checking at scope exit
    const allocator = gpa.allocator();

    // 2. Explicit Dependency Injection
    // The ArrayList cannot exist in a vacuum; it *must* hold a reference to our allocator.
    var list = std.ArrayList(i32).init(allocator);
    defer list.deinit(); // Explicit cleanup

    // 3. Explicit Control Flow and Error Handling
    // Appending can fail if the system runs out of memory. 
    // Zig forces you to acknowledge this with the `try` keyword. 
    // There are no invisible exceptions—it explicitly bubbles up the call stack.
    try list.append(42);
    try list.append(1337);

    std.debug.print("Elements: {any}\\n", .{list.items});
}
```

Defining your allocation strategy explicitly makes managing memory straightforward, and the `defer` keyword keeps cleanup simple and clean.

---

### Explicit I/O Subsystem

```zig
const std = @import("std");

pub fn main() !void {
    // 1. Explicitly acquire a handle to Standard Output
    // This doesn't happen automatically; you must ask the OS subsystem for it.
    const stdout_file = std.io.getStdOut();
    
    // 2. Initialize a buffered Writer stream
    // Zig separates the raw file descriptor from the stream interface.
    // If you want buffering to prevent frequent system calls, you wrap it explicitly.
    var bw = std.io.bufferedWriter(stdout_file.writer());
    const stdout = bw.writer();

    // 3. Perform the I/O operation
    // Because I/O can always fail (e.g., broken pipe, disk full), 
    // the compiler forces you to handle the error with 'try'.
    try stdout.print("Hello, {s}!\\n", .{"systems engineering"});

    // 4. Explicitly flush the buffer to the OS
    // With buffered I/O, you control exactly when the syscall happens.
    try bw.flush(); 
}
```

The code above is essentially how you write a production-grade `printf` in Zig. You might look at this and think it's tedious boilerplate. You might even be right. But I think it's beautiful.

What it actually does is force you to initialize your I/O devices with explicit implementation details. You get absolute control over your code. If you think that's "too much control," then go back to doing web development at some bloated startup, selling over-engineered solutions to non-existent problems using 100K lines of boilerplate for basic CRUD apps.

### How `std.io` Actually Works Under the Hood (Peak Comptime)

If you look at how other languages handle I/O, they usually rely on virtual tables (vtables) or interface types for dynamic dispatch. Rust has `std::io::Write` trait objects; Go has `io.Writer` interfaces. This works, but it adds runtime overhead.

Zig doesn't do dynamic dispatch here. Instead, it uses `comptime` duck typing to construct writers and readers on the fly.

In the standard library, `std.io.Writer` is just a function that returns a type:

```zig
pub fn Writer(
    comptime Context: type,
    comptime Error: type,
    comptime writeFn: fn (context: Context, bytes: []const u8) Error!usize,
) type {
    return struct {
        context: Context,
        pub const ErrorSet = Error;
        const Self = @this();

        pub fn write(self: Self, bytes: []const u8) Error!usize {
            return writeFn(self.context, bytes);
        }
        
        // ... provides helper methods like print(), writeAll(), writeByte() at compile-time
    };
}
```

This is insanely powerful. Any struct that implements a `write` function can be instantly wrapped into a full-featured `Writer` at compile time. No vtables, no interfaces, and zero virtual call overhead. The compiler resolves it all down to direct function calls.

For a project like `glu`—where I'm building a lightweight robotics communication framework to replace the bloated monster that is ROS2—this is a lifesaver. When publishing telemetry or serializing command payloads over TCP/UDP sockets or serial lines, I can wrap raw handles in custom writers without paying any abstraction tax. Every single byte goes exactly where it needs to, precisely when it needs to, with absolute predictability.

---

## Build Systems: What Got Me Into Zig in the First Place

This is the main reason I got into Zig. I love C, but its build system options are enough to drive anyone crazy. You are stuck wrestling with CMake or Makefiles, and you have to manually install, build, and link your third-party dependencies. (Though to be honest, a big reason I got decent at programming was because I used to build C projects with zero external dependencies out of sheer laziness to avoid the linking nightmare).

But when you want to build actual, real-world systems, you need a solid build system. Zig gives you that—and it doubles as an amazing build system for C and C++ projects too.

While I haven't used the full C/C++ build system integration yet, importing libraries like `cuda` and `vulkan` into Zig was incredibly smooth. And for my latest project, `glu`, exporting my Zig API functions and types back into C has been a flawless experience.

---

## Zig is Not Perfect

I've spent this entire post trying to convince you why Zig is great and why you should use it. But it is not perfect. Nothing is.

For one, I'm definitely not a Zig expert yet, so I'm still discovering its rough edges. But the most obvious challenge right now is that Zig has not reached `v1.0.0`. With every new release, parts of the standard library API are broken or deprecated. It's a backward-compatibility nightmare. You might pull in a third-party package only for it to fail to compile because the library was written for Zig `v0.15.0` and you're using `v0.16.0`.

On top of that, the community is still relatively small. They are brilliant and incredibly helpful people, but it's a small crowd nonetheless.

---

## Will I Use Zig for Large Projects?

Absolutely. I am currently building a robotics communication framework called `glu` from scratch. The goal is to make it a lightweight, high-performance alternative to ROS2—a framework that is widely disliked by indie developers and frustrating for labs that need maximum performance without the ROS2 bloat.

I'm writing `glu` entirely in Zig. Will the backward-compatibility breaks bite me in the ass? Probably. But the language is so good that it's a risk I'm more than willing to take. I want `glu` to be a rock-solid, reliable system for real production work.

---

## A Final Note on AI and Zig

Because Zig is a younger language and still changes rapidly, LLMs struggle with it. LLMs are essentially advanced copycats, and since there aren't millions of Zig repositories to copy from yet, they often write broken code.

But if you want to learn a systems language like Zig, you should have the passion to write most of the heavy-lifting logic yourself anyway. Use the AI to spit out the boring boilerplate, and write the real code on your own."""


saasPost : String
saasPost =
    """# What I Learnt Building a SaaS (And Why the Startup Scene is Cancer)

For the past few months, I've been building a SaaS project with some college mates. To be completely honest, I've always found the modern SaaS scene incredibly stupid. Most projects look like absolute garbage to me—glorified AI wrappers attempting to solve problems that don't exist. Why would anyone need an "AI Alarm Clock"? Human beings are born with a free piece of technology called a biological clock. But hey, maybe the flagship humans are out of production, and the new economical models don't come with that feature built-in. Who am I to judge?

Actually, I will judge. The entire startup ecosystem is a disease. It's a playground where marketing, hype, and VC-pleasing buzzwords weigh infinitely more than the actual value or engineering quality of the solution. It's the natural result of late-stage capitalism: a system that doesn't care about creating things that are useful or elegant, but instead incentivizes grifters to build bloated, useless tools just to extract subscription fees.

This is the story of how we took a failed, hype-driven hackathon project, stripped away the AI bullshit, and built a real-time API security platform called Argos—along with what I learnt about code, useless people, and why the tech industry is broken.

---

## 1. The Hackathon Genesis: An AI SIEM Mirage

The journey started five months ago at a college hackathon. A teammate opened his phone, prompted ChatGPT (or Gemini, I can't remember), and immediately declared that our project would be a shiny "AI SIEM Solution." I've always found conventional security analytics incredibly boring, but as the lead for Machine Learning and Backend Engineering, I had to look into how SIEMs actually function under the hood.

I quickly realized we needed to pivot. Instead of post-incident log analysis (SIEM)—which is just looking at the ashes of your server after it already burned down—we needed real-time protection at the application layer. An inline API security solution.

Because of extreme time constraints—and the fact that I hadn't slept for three days straight—I wrote some of the worst code of my life. The initial architecture was an absolute disaster:

```
+------------------+      Unstructured JSON      +----------------------+
| Inbound HTTP Req | --------------------------> |   Naive LLM Prompt   |
+------------------+                             +----------------------+
                                                            |
                                                            v
+------------------+       Massive Latency       +----------------------+
|  Blocked / Pass  | <-------------------------- |  "Retarded" SOC Bot  |
+------------------+                             +----------------------+
```

The pipeline took a raw JSON request, passed it wholesale to a massive LLM with a flimsy prompt, and asked it to act like a tier-one SOC analyst. No schema constraints, no input validation, and zero deterministic parsing. It was slow as hell, expensive as fuck, and completely impractical for real-world production traffic. It was the perfect representation of modern "AI engineering"—retarded, bloated, and useless.

While waiting for the judges to inevitably smoke us during presentation day, the practical solution hit me. I thought about Stripe. They don't make you reroute your whole network through a slow proxy; they provide lightweight, native SDKs that drop right into your backend code to handle the heavy lifting.

---

## 2. The Architecture Shift: Go Backend & Decoupled SDKs

We got cooked at the hackathon, but the technical challenge stuck with me. Even though the business side of SaaS makes me sick, I thought building the actual engine would be a fun engineering exercise.

I chose Go for the backend engine. I've never been a pure backend engineer—building CRUD APIs doesn't give me the same rush as writing compilers, operating systems, or low-level systems infrastructure—but the team dynamics forced my hand. Out of a five-person team, only my close friend and I were actual builders. The other three were non-contributing passengers who did absolutely nothing but talk, show up to meetings, and repeat corporate jargon they probably read on LinkedIn.

To make the platform a reality without losing my mind, we had to build fast and bypass the dead weight.

Our core architectural blueprint decoupled the application runtime from the detection cluster using language-specific middlewares (SDKs):

```
   User Request
        |
        v
+---------------------------------------+
| Your Web App Runtime (Node/Python/Go) |
|                                       |
|  +---------------------------------+  |
|  |     Argos Middleware / SDK      |  |
|  +---------------------------------+  |
+---------------------------------------+
        |
        | Asynchronous / Synchronous Channel
        v
+---------------------------------------+
|       Argos Go Detection Engine       |
|                                       |
|  [Regex] -> [Statistical] -> [ML/DL]  |
+---------------------------------------+
```

To standardize behavioral tracking and model training, we normalized all incoming HTTP metadata into a strictly typed, unified exchange format. Here is a conceptual look at how our lightweight SDK middleware intercepts, extracts, and dispatches payload telemetry without blocking the hot-path:

```go
package argos

import (
	"bytes"
	"io"
	"net/netip"
	"net/http"
	"time"
)

type TelemetryPayload struct {
	Method    string            `json:"method"`
	Path      string            `json:"path"`
	Headers   map[string]string `json:"headers"`
	Body      string            `json:"body"`
	RemoteIP  string            `json:"remote_ip"`
	Timestamp int64             `json:"timestamp"`
}

func ArgosMiddleware(client *ArgosClusterClient) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			var bodyBytes []byte
			if r.Body != nil {
				bodyBytes, _ = io.ReadAll(r.Body)
				r.Body = io.NopCloser(bytes.NewBuffer(bodyBytes))
			}

			payload := TelemetryPayload{
				Method:    r.Method,
				Path:      r.URL.Path,
				Headers:   extractHeaders(r.Header),
				Body:      string(bodyBytes),
				RemoteIP:  r.RemoteAddr,
				Timestamp: time.Now().UnixNano(),
			}

			// Run in a goroutine to avoid blocking the main request thread
			go client.Analyze(payload)

			next.ServeHTTP(w, r)
		})
	}
}
```

---

## 3. Optimizing the Pipeline: Mechanical Pentesting

During my university final exams, I needed a productive way to procrastinate. Instead of studying legacy rendering hooks for my Computer Graphics course, I started learning web application penetration testing.

I quickly realized something critical: Web pentesting is deeply mechanical. When an attacker or an automated scanner maps an API, they systematically spray known, highly predictable structural patterns against your endpoints to check for vulnerabilities (SQLi, XSS, Path Traversal).

If you can catch those mechanical trials on the ultra-fast hot path using a strict cascade of deterministic filters, you don't need a heavy deep learning model or a slow LLM for standard exploitation attempts.

### The Multi-Tier Inspection Stack

We threw the single, slow LLM bottleneck in the trash and built a multi-tier pipeline:

1. **Deterministic Filter (Regex & Tokenizer)**: Instantly drops obvious, raw signatures (e.g., `' OR 1=1 --`, `<script>`).
2. **Statistical Analyzer**: Evaluates entropy variations, character distribution shifts, and structural anomalies in the payload lengths.
3. **Machine Learning / Deep Learning Module**: Processes deep contextual threats only when the first two layers raise suspicion flags.

```
Incoming Payload
      |
      v
  +----------------------------------+
  | Tier 1: Deterministic Regex/Tok  | ---> [Signature Match] -> Immediate IP Block
  +----------------------------------+
      | Clean
      v
  +----------------------------------+
  | Tier 2: Statistical Entropy      | ---> [Anomalous Deviation] -> Trigger ML/DL
  +----------------------------------+
      | Clean
      v
  +----------------------------------+
  | Tier 3: Contextual ML/DL Models  | ---> [Malicious Intent] -> Action & Flag
  +----------------------------------+
```

By instantly dropping an automated firewall block on the attacker's IP the moment a mechanical signature is hit, we break the attacker's feedback loop. If a malicious actor has to rotate their proxy or IP address after every single exploit variation, the cost of attack skyrockets, and they move on.

---

## 4. What I Learnt (The Hard Way)

**Capitalism is the Cancer of Software**:
As a developer, I love pure engineering, solving complex algorithmic bottlenecks, and writing clean, minimal code. But in our capitalistic society, none of that matters. Capitalism does not reward good engineering; it rewards marketing grift. A bulletproof software engine is useless in the market if you cannot write slick copy, buy ads, and convince corporate managers to buy it. This is why I absolutely despise the startup scene. It forces talented builders to stop building and start selling, converting engineering passion into corporate marketing noise.

**Most People Just Want a Free Ride**:
You will quickly learn that most people suck. In group projects, hackathons, and startups, you will always find passengers—people who want the title, the equity, and the glory, but won't write a single line of code. They will spend hours talking about "strategy" and "positioning" to cover up the fact that they have zero technical skills. Build exclusively with active creators, protect your peace, and kick the dead weight out early. As Drake put it in *Fair Trade*:

> "I've been losing friends and finding peace, honestly that sounds like a fair trade to me."

**Backend is Fine, but It's Not Compilers**:
Go is a highly concurrent, practical language for processing request streams, but backend development still lacks the intellectual beauty of compiler design or low-level systems. At the end of the day, building a SaaS often feels like assembling pre-existing puzzle pieces. But if you have to do it, at least do it without the typical corporate bloat.

---

## The Reality of the Roadmap

The platform is live at [argossecops.com](https://argossecops.com). We are using an open-core model, keeping our core high-concurrency detection engine proprietary while open-sourcing our client SDKs.

Is it a revolutionary breakthrough in computer science? No. At its core, it's just a fast, clean, multi-tiered firewall and detection system. But unlike the bloated, VC-backed "AI security" garbage polluting the internet today, it actually works, it doesn't kill your request latency, and it doesn't feed your sensitive data to OpenAI.

If you're a developer who cares about performance and wants to secure your APIs without adopting 200MB of dependencies and a slow AI proxy, check it out. Or don't. At least the code is clean."""

